# Required:
	[[plugins]]
	repo = 'Shougo/dein.vim'


# Plugins

	# コードを自動的に入力補完してくれる
	[[plugins]]
	repo = 'Shougo/neocomplete'

	# スニペット
	[[plugins]]
	repo =  'Shougo/neosnippet'
	[[plugins]]
	repo = 'Shougo/neosnippet-snippets'

	# ファイル操作
	[[plugins]]
	repo = 'Shougo/unite.vim'

	[[plugins]]
	repo = 'Shougo/neomru.vim'

	# unite.vimと依存関係にあるらしい
	[[plugins]]
	repo = 'Shougo/vimproc.vim'
	build = 'make'

	# ファイルをtree表示してくれる
	[[plugins]]
	repo =  'scrooloose/nerdtree'

	# コメントON/OFFを手軽に実行
	[[plugins]]
	repo =  'tomtom/tcomment_vim'

	# シングルクオートとダブルクオートの入れ替え等
	[[plugins]]
	repo =  'tpope/vim-surround'

	# インデントに色を付けて見やすくする
	#[[plugins]]
	#repo =  'nathanaelkane/vim-indent-guides'
	#	# vimを立ち上げたときに、自動的にvim-indent-guidesをオンにする
	#	hock_add = 'let g:indent_guides_enable_on_vim_startup = 1'

	# ログファイルを色づけしてくれる
	[[plugins]]
	repo =  'vim-scripts/AnsiEsc.vim'

	# 行末の半角スペースを可視化
	[[plugins]]
	repo =  'bronson/vim-trailing-whitespace'

	# インデントの可視化
	#[[plugins]]
	#repo = 'Yggdroot/indentLine'

	# 下のステータスラインを見やすくする(設定は下に)
	[[plugins]]
	repo =  'itchyny/lightline.vim'

	# HTML5のタグに色を付ける
	[[plugins]]
	repo =  'othree/html5.vim'

	# JSのタグに色を付ける
	[[plugins]]
	repo =  'taichouchou2/vim-javascript'

	# CSS3のタグに色を付ける
	[[plugins]]
	repo =  'hail2u/vim-css3-syntax'

	# Sass
	#[[plugins]]
	#repo =  'AtsushiM/search-parent.vim'
	#repo =  'AtsushiM/sass-compile.vim'

	# Emmet
	[[plugins]]
	repo =  'mattn/emmet-vim'

# Colors

	# molokai
	[[plugins]]
	repo = 'tomasr/molokai'

	# solarized
	[[plugins]]
	repo = 'altercation/vim-colors-solarized'

	# monokai
	[[plugins]]
	repo = 'sickill/vim-monokai'

